[project]
name = "ventureval-opensource"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckduckgo-search>=8.1.1",
    "fpdf>=1.7.2",
    "google-adk>=1.25.0",
    "plotly>=6.5.2",
    "python-dotenv>=1.2.2",
    "streamlit>=1.54.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.1",
]
