import re
from datetime import datetime
from fpdf import FPDF


class VenturePDF(FPDF):
    def header(self):
        self.set_fill_color(248, 250, 252)
        self.rect(0, 0, self.w, self.h, style="F")

        if self.page_no() > 1:
            self.set_fill_color(0, 51, 102)
            self.rect(0, 0, self.w, 15, style="F")

            self.set_y(5)
            self.set_font("helvetica", "B", 10)
            self.set_text_color(255, 255, 255)  # White text on the blue bar
            self.cell(0, 5, "VentureVal AI: Executive Summary", align="R")
            self.ln(15)

    def footer(self):
        if self.page_no() > 1:
            self.set_y(-15)
            self.set_font("helvetica", style="I", size=8)
            self.set_text_color(150, 150, 150)
            self.cell(
                0,
                10,
                f"Page {self.page_no()} | Generated by Keshav Agarwal's VentureVal AI",
                align="C",
            )


def generate_swot_pdf(idea: str, report_text: str) -> bytes:
    pdf = VenturePDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # Cover Page
    pdf.ln(50)
    pdf.set_font("helvetica", "B", 24)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 15, "VentureVal AI", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_font("helvetica", "", 16)
    pdf.set_text_color(100, 100, 100)  # Dark gray
    pdf.cell(
        0,
        10,
        "Autonomous Market Validation Report",
        new_x="LMARGIN",
        new_y="NEXT",
        align="C",
    )

    pdf.ln(30)
    pdf.set_font("helvetica", "I", 12)

    safe_idea = " ".join(
        [w if len(w) < 60 else w[:60] + " " + w[60:] for w in idea.split()]
    )
    pdf.multi_cell(0, 8, f"Target Business Idea:\n{safe_idea}", align="C")

    pdf.ln(40)
    pdf.set_font("helvetica", "", 10)
    pdf.cell(
        0,
        6,
        f"Date Generated: {datetime.now().strftime('%B %d, %Y')}",
        align="C",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(
        0, 6, "Prepared by: Keshav Agarwal", align="C", new_x="LMARGIN", new_y="NEXT"
    )

    # Report Body
    pdf.add_page()
    lines = report_text.split("\n")

    for line in lines:
        line = line.rstrip()

        if not line.strip():
            pdf.ln(3)
            continue

        pdf.set_x(pdf.l_margin)

        if re.match(r"^[-*_=\s]{3,}$", line.strip()):
            pdf.ln(3)
            pdf.set_draw_color(200, 200, 200)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(3)
            continue

        if line.strip().startswith("#"):
            clean_heading = re.sub(r"^#+\s*", "", line.strip())
            pdf.set_font("helvetica", "B", 14)
            pdf.set_text_color(0, 51, 102)
            pdf.ln(4)
            line = clean_heading
        else:
            pdf.set_font("helvetica", "", 11)
            pdf.set_text_color(0, 0, 0)

        # Color-Coded SWOT Logic
        lower_line = line.lower()
        if "strength" in lower_line:
            pdf.set_text_color(0, 128, 0)
        elif "weakness" in lower_line:
            pdf.set_text_color(204, 0, 0)
        elif "opportunity" in lower_line:
            pdf.set_text_color(0, 102, 204)
        elif "threat" in lower_line:
            pdf.set_text_color(204, 102, 0)

        clean_line = line.replace("**", "")
        clean_line = clean_line.replace("•", "-")  # Fix LLM Unicode bullet points

        words = clean_line.split(" ")
        safe_words = [w if len(w) < 60 else w[:60] + " " + w[60:] for w in words]
        clean_line = " ".join(safe_words)

        safe_line = clean_line.encode("latin-1", "replace").decode("latin-1")

        # 7. Print with bulletproof fallback
        try:
            pdf.multi_cell(0, 7, safe_line)
        except Exception as e:
            print(f"Fallback triggered for line: {e}")
            pdf.set_x(pdf.l_margin)
            pdf.write(7, safe_line + "\n")

    return bytes(pdf.output())
